import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FileText, Shield, Eye, Edit3, Download, Loader2 } from "lucide-react";
import { useAuth } from "@/hooks/use-auth";
import { useToast } from "@/hooks/use-toast";
import { pdf } from "@react-pdf/renderer";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { createElement } from "react";
import { format, subDays } from "date-fns";

const pdfStyles = StyleSheet.create({
  page: { padding: 40, fontSize: 9, fontFamily: "Helvetica", color: "#1a1a1a" },
  header: { marginBottom: 16 },
  title: { fontSize: 16, fontFamily: "Helvetica-Bold", color: "#0f172a", marginBottom: 4 },
  subtitle: { fontSize: 9, color: "#64748b", marginBottom: 12 },
  divider: { borderBottomWidth: 2, borderBottomColor: "#0f172a", marginBottom: 12 },
  tableHeader: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#94a3b8", paddingBottom: 4, marginBottom: 4 },
  tableHeaderCell: { fontSize: 7, fontFamily: "Helvetica-Bold", color: "#64748b", textTransform: "uppercase" },
  tableRow: { flexDirection: "row", paddingVertical: 3, borderBottomWidth: 0.5, borderBottomColor: "#e2e8f0" },
  tableCell: { fontSize: 8 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40 },
  footerText: { fontSize: 7, color: "#94a3b8", textAlign: "center" },
  emptyText: { fontSize: 10, color: "#94a3b8", marginTop: 20, textAlign: "center" },
});

function ReportDocument({ title, dateRange, columns, rows }: { title: string; dateRange: string; columns: { label: string; width: number }[]; rows: any[][] }) {
  return (
    <Document>
      <Page size="LETTER" style={pdfStyles.page}>
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.title}>{title}</Text>
          <Text style={pdfStyles.subtitle}>Period: {dateRange} | Generated: {format(new Date(), "MMM d, yyyy h:mm a")}</Text>
        </View>
        <View style={pdfStyles.divider} />
        {rows.length > 0 ? (
          <>
            <View style={pdfStyles.tableHeader}>
              {columns.map((col, i) => (
                <Text key={i} style={[pdfStyles.tableHeaderCell, { width: col.width }]}>{col.label}</Text>
              ))}
            </View>
            {rows.slice(0, 100).map((row, ri) => (
              <View key={ri} style={pdfStyles.tableRow}>
                {row.map((cell: string, ci: number) => (
                  <Text key={ci} style={[pdfStyles.tableCell, { width: columns[ci]?.width || 80 }]}>{cell}</Text>
                ))}
              </View>
            ))}
            {rows.length > 100 && <Text style={pdfStyles.emptyText}>...and {rows.length - 100} more records</Text>}
          </>
        ) : (
          <Text style={pdfStyles.emptyText}>No records found for this period.</Text>
        )}
        <View style={pdfStyles.footer}>
          <Text style={pdfStyles.footerText}>Generated by ClaimShield Health | {title} | {dateRange}</Text>
        </View>
      </Page>
    </Document>
  );
}

const REPORTS = [
  {
    id: "access",
    title: "Access Report",
    description: "Log of all patient and claim record access during the reporting period.",
    icon: Eye,
    columns: [
      { label: "Timestamp", width: 110 },
      { label: "User", width: 120 },
      { label: "Action", width: 80 },
      { label: "Record", width: 80 },
      { label: "Description", width: 150 },
    ],
    mapRow: (r: any) => [
      r.created_at ? format(new Date(r.created_at), "MMM d, yyyy h:mm a") : "—",
      r.user_email || r.performed_by || "System",
      r.activity_type || "—",
      r.claim_id ? `Claim ${r.claim_id.slice(0, 8)}` : r.patient_id ? `Patient ${r.patient_id.slice(0, 8)}` : "—",
      r.description || "—",
    ],
  },
  {
    id: "edit-history",
    title: "Edit History Report",
    description: "Record of all field-level edits to billing data during the reporting period.",
    icon: Edit3,
    columns: [
      { label: "Timestamp", width: 100 },
      { label: "User", width: 100 },
      { label: "Field", width: 70 },
      { label: "Old Value", width: 85 },
      { label: "New Value", width: 85 },
      { label: "Description", width: 100 },
    ],
    mapRow: (r: any) => [
      r.created_at ? format(new Date(r.created_at), "MMM d, yyyy h:mm a") : "—",
      r.user_email || r.performed_by || "System",
      r.field || "—",
      r.old_value || "—",
      r.new_value || "—",
      r.description || "—",
    ],
  },
  {
    id: "export",
    title: "Export Report",
    description: "All claim exports and PDF generations during the reporting period.",
    icon: Download,
    columns: [
      { label: "Timestamp", width: 110 },
      { label: "User", width: 120 },
      { label: "Claim ID", width: 80 },
      { label: "Amount", width: 70 },
      { label: "Status", width: 70 },
      { label: "Description", width: 100 },
    ],
    mapRow: (r: any) => [
      r.created_at ? format(new Date(r.created_at), "MMM d, yyyy h:mm a") : "—",
      r.user_email || r.performed_by || "System",
      r.claim_id ? r.claim_id.slice(0, 8) : "—",
      r.amount ? `$${Number(r.amount).toLocaleString()}` : "—",
      r.claim_status || "—",
      r.description || "—",
    ],
  },
  {
    id: "claims-integrity",
    title: "Claims Integrity Report",
    description: "All claims created during the reporting period with status and risk assessment.",
    icon: Shield,
    columns: [
      { label: "Claim ID", width: 70 },
      { label: "Patient", width: 100 },
      { label: "Status", width: 60 },
      { label: "Risk", width: 50 },
      { label: "Amount", width: 60 },
      { label: "Service Date", width: 80 },
      { label: "Created", width: 80 },
    ],
    mapRow: (r: any) => [
      r.id?.slice(0, 8) || "—",
      r.patient_name || "Unknown",
      r.status || "—",
      r.readiness_status || "—",
      r.amount ? `$${Number(r.amount).toLocaleString()}` : "—",
      r.service_date ? format(new Date(r.service_date), "MMM d, yyyy") : "—",
      r.created_at ? format(new Date(r.created_at), "MMM d, yyyy") : "—",
    ],
  },
];

function ReportCard({ report }: { report: typeof REPORTS[0] }) {
  const { toast } = useToast();
  const [startDate, setStartDate] = useState(format(subDays(new Date(), 30), "yyyy-MM-dd"));
  const [endDate, setEndDate] = useState(format(new Date(), "yyyy-MM-dd"));
  const [generating, setGenerating] = useState(false);

  async function handleGenerate() {
    setGenerating(true);
    try {
      const params = new URLSearchParams({ startDate: new Date(startDate).toISOString(), endDate: new Date(endDate + "T23:59:59").toISOString() });
      const res = await fetch(`/api/billing/compliance-report/${report.id}?${params}`, { credentials: "include" });
      if (!res.ok) throw new Error("Failed to fetch report data");
      const data = await res.json();
      const rows = data.map(report.mapRow);
      const dateRange = `${format(new Date(startDate), "MMM d, yyyy")} – ${format(new Date(endDate), "MMM d, yyyy")}`;

      const doc = createElement(ReportDocument, { title: report.title, dateRange, columns: report.columns, rows });
      const blob = await pdf(doc).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${report.id}_report_${startDate}_${endDate}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({ title: `${report.title} downloaded`, description: `${data.length} records included.` });
    } catch (err: any) {
      toast({ title: "Report generation failed", description: err.message, variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  }

  const Icon = report.icon;

  return (
    <Card data-testid={`card-report-${report.id}`}>
      <CardHeader className="pb-3">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-lg bg-muted flex items-center justify-center">
            <Icon className="h-5 w-5 text-muted-foreground" />
          </div>
          <div>
            <CardTitle className="text-base">{report.title}</CardTitle>
            <CardDescription className="text-xs mt-0.5">{report.description}</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="pt-0">
        <div className="flex flex-wrap items-end gap-3">
          <div className="space-y-1">
            <Label className="text-xs">From</Label>
            <Input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="w-36" data-testid={`input-${report.id}-start`} />
          </div>
          <div className="space-y-1">
            <Label className="text-xs">To</Label>
            <Input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="w-36" data-testid={`input-${report.id}-end`} />
          </div>
          <Button onClick={handleGenerate} disabled={generating} size="sm" className="gap-1.5" data-testid={`button-generate-${report.id}`}>
            {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}
            {generating ? "Generating..." : "Generate PDF"}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

export default function ComplianceReportsPage() {
  const { user } = useAuth();

  if (user?.role !== "admin") {
    return (
      <div className="p-6">
        <Card>
          <CardContent className="p-8 text-center">
            <Shield className="h-10 w-10 mx-auto text-muted-foreground mb-3" />
            <h2 className="text-lg font-semibold" data-testid="text-admin-required">Admin access required</h2>
            <p className="text-muted-foreground text-sm mt-1">Only administrators can access compliance reports.</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-semibold" data-testid="text-page-title">Compliance Reports</h1>
        <p className="text-muted-foreground">HIPAA and audit compliance reporting</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {REPORTS.map((r) => <ReportCard key={r.id} report={r} />)}
      </div>
    </div>
  );
}
