export const allPayers = [
  // Major National Payers
  "UnitedHealthcare",
  "Anthem Blue Cross Blue Shield",
  "Aetna",
  "Cigna",
  "Humana",
  "Kaiser Permanente",
  "Centene",
  "Molina Healthcare",
  "CVS Health / Aetna",
  "Elevance Health",
  
  // Blue Cross Blue Shield Plans (Regional)
  "Blue Cross Blue Shield of Texas",
  "Blue Cross Blue Shield of California",
  "Blue Cross Blue Shield of Florida",
  "Blue Cross Blue Shield of Illinois",
  "Blue Cross Blue Shield of Michigan",
  "Blue Cross Blue Shield of New York",
  "Blue Cross Blue Shield of Pennsylvania",
  "Blue Cross Blue Shield of Georgia",
  "Blue Cross Blue Shield of North Carolina",
  "Blue Cross Blue Shield of Tennessee",
  "Blue Cross Blue Shield of Arizona",
  "Blue Cross Blue Shield of Massachusetts",
  "Blue Cross Blue Shield of Ohio",
  "Independence Blue Cross",
  "Highmark Blue Cross Blue Shield",
  "CareFirst BlueCross BlueShield",
  "Excellus BlueCross BlueShield",
  "Horizon Blue Cross Blue Shield of New Jersey",
  "Regence Blue Cross Blue Shield",
  "Premera Blue Cross",
  
  // Government Programs
  "Medicare",
  "Medicare Advantage",
  "Medicaid",
  "Tricare",
  "Veterans Affairs (VA)",
  "CHAMPVA",
  
  // Regional & Specialty Payers
  "Health Care Service Corporation (HCSC)",
  "Wellcare",
  "Bright Health",
  "Oscar Health",
  "Clover Health",
  "Devoted Health",
  "Alignment Healthcare",
  "Alignment Health Plan",
  "Ambetter",
  "Amerigroup",
  "WellPoint",
  "Carefirst",
  "UPMC Health Plan",
  "Geisinger Health Plan",
  "Priority Health",
  "Health Alliance",
  "Medical Mutual",
  "SelectHealth",
  "Sanford Health Plan",
  "PreferredOne",
  "Medica",
  "HealthPartners",
  "Quartz Health Solutions",
  "Security Health Plan",
  "Dean Health Plan",
  "Group Health Cooperative",
  "Providence Health Plan",
  "Moda Health",
  "PacificSource Health Plans",
  "Cambia Health Solutions",
  "Regence BlueCross BlueShield of Oregon",
  "LA Care Health Plan",
  "Health Net",
  "CalOptima",
  "Inland Empire Health Plan",
  "Partnership HealthPlan",
  "San Francisco Health Plan",
  "Contra Costa Health Plan",
  "Community Health Group",
  "Sharp Health Plan",
  "Western Health Advantage",
  "Chinese Community Health Plan",
  "SCAN Health Plan",
  "Brand New Day",
  "Central Health Plan of California",
  
  // Behavioral Health Specific
  "Magellan Healthcare",
  "Optum Behavioral Health",
  "Beacon Health Options",
  "ComPsych",
  "New Directions Behavioral Health",
  "Carelon Behavioral Health",
  "Lyra Health",
  "Spring Health",
  "Headway",
  "Alma",
  "Cerebral",
  "Talkspace",
  
  // Workers Comp & Specialty
  "The Hartford",
  "Travelers",
  "Liberty Mutual",
  "Sedgwick",
  "Gallagher Bassett",
  "CorVel",
  
  // Pharmacy Benefit Managers (often involved in claims)
  "Express Scripts",
  "CVS Caremark",
  "OptumRx",
  "Elixir",
  "MedImpact",
  "Prime Therapeutics",
  
  // Third Party Administrators
  "HealthSCOPE Benefits",
  "Meritain Health",
  "HealthEZ",
  "Allegiance",
  "EBMS",
  "CoreSource",
  "Trustmark",
  "DataPath",
  "Employee Benefit Management Services",
  
  // Medicare Advantage Plans
  "Devoted Health Medicare Advantage",
  "Clover Health Medicare Advantage",
  "Alignment Health Medicare",
  "Bright Health Medicare",
  "Wellcare Medicare Advantage",
  "Humana Medicare Advantage",
  "UnitedHealthcare Medicare Advantage",
  "Aetna Medicare",
  "Cigna Medicare",
  "Kaiser Medicare",
  "Blue Cross Medicare Advantage",
  "SCAN Medicare",
  "Molina Medicare",
  "Centene Medicare",
  
  // Medicaid Managed Care
  "Amerigroup Medicaid",
  "Molina Medicaid",
  "Centene Medicaid",
  "UnitedHealthcare Community Plan",
  "Anthem Medicaid",
  "WellCare Medicaid",
  "Sunshine Health",
  "Superior HealthPlan",
  "Cook Children's Health Plan",
  "Community First Health Plans",
  "Driscoll Health Plan",
  "FirstCare Health Plans",
  "Parkland Community Health Plan",
  "Texas Children's Health Plan",
  
  // Additional Major Payers
  "Tufts Health Plan",
  "Harvard Pilgrim Health Care",
  "Point32Health",
  "ConnectiCare",
  "EmblemHealth",
  "MVP Health Care",
  "Capital District Physicians Health Plan (CDPHP)",
  "Fidelis Care",
  "Healthfirst",
  "MetroPlus Health Plan",
  "Affinity Health Plan",
  "AmeriHealth",
  "Capital BlueCross",
  "Geisinger",
  "Gateway Health",
  "Buckeye Health Plan",
  "CareSource",
  "Paramount Health Care",
  "SummaCare",
  "Aultcare",
  "Mercy Health",
  "PHP (Physicians Health Plan)",
  "McLaren Health Plan",
  "HAP (Health Alliance Plan)",
  "Blue Care Network",
  "Meridian Health Plan",
  "Total Health Care",
  "Neighborhood Health Plan of Rhode Island",
  "Blue Cross & Blue Shield of Rhode Island",
  "Tufts Health Together",
  "Community Health Options",
  "Martin's Point Health Care",
  "Anthem HealthKeepers",
  "Optima Health",
  "Virginia Premier",
  "Sentara Health Plans",
  "Piedmont Community Health Plan",
  "AmeriHealth Caritas",
  "Keystone First",
  "Health Partners Plans",
  "Coventry Health Care",
];

export const payerCount = allPayers.length;
