import{test}from'node:test';import assert from'node:assert/strict';import{calculateCost,buildWorkflowPlan,matchesFilter,choices}from'../public/toolkit.mjs';import{createMarketingServer}from'../server.mjs';import{readFile}from'node:fs/promises';
const v={volume:100,prep:10,corrections:20,minutes:15,rate:30,'compare-prep':8,'compare-corrections':20,'compare-minutes':12,fees:200,implementation:50};
test('cost math includes correction work, fees and negative differences',()=>{const r=calculateCost(v,true);assert.equal(r.labor,650);assert.equal(r.comparisonTotal,770);assert.equal(r.difference,-120);assert.equal(calculateCost({...v,rate:0}).labor,0);});
test('rejects missing, fractional counts, negative, infinite and excessive inputs',()=>{for(const value of ['',null,undefined,-1,Infinity,NaN,1e99,.5])assert.throws(()=>calculateCost({...v,volume:value}));assert.throws(()=>calculateCost({...v,fees:''},true));assert.ok(Number.isFinite(calculateCost({...v,volume:1000000,prep:10080,rate:10000}).labor));});
test('all 128 planner combinations have valid scope and no unverified promise',()=>{let count=0;for(const program of Object.keys(choices.program))for(const volume of Object.keys(choices.volume))for(const focus of Object.keys(choices.focus))for(const baseline of Object.keys(choices.baseline)){const p=buildWorkflowPlan({program,volume,focus,baseline});assert.equal(p.steps.length,5);assert.match(p.scope,/not confirmation/);count++;}assert.equal(count,128);assert.throws(()=>buildWorkflowPlan({program:'unknown'}));});
test('filters handle whitespace, case and combined categories',()=>{assert.ok(matchesFilter('Authorization missing','Review',' AUTHORIZATION ','Review'));assert.equal(matchesFilter('Authorization missing','Review','authorization','Prepare'),false);assert.ok(matchesFilter('abc','Review','','All stages'));});
test('all pages, assets, internal links and fragments resolve; public brand and SEO are consistent',async()=>{const server=createMarketingServer({PUBLIC_RELEASE_APPROVED:'true',PUBLIC_ORIGIN:'https://www.resolta.ai'});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;try{const routes=JSON.parse(await readFile(new URL('../routes.json',import.meta.url)));const pages=new Map();for(const route of routes){const r=await fetch(origin+route.path);assert.equal(r.status,200);const html=await r.text();pages.set(route.path,html);assert.doesNotMatch(html,/claim\s?shield|rivana|GTM Drive|class="notice"/i);assert.equal([...html.matchAll(/<h1[ >]/g)].length,1);assert.match(html,/sales@resolta.ai/);assert.ok(html.includes(`rel="canonical" href="https://www.resolta.ai${route.path}"`));const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);}
const links=new Set();for(const[path,html]of pages)for(const match of html.matchAll(/(?:href|src)="([^" ]+)"/g)){const url=new URL(match[1],origin+path);if(url.origin===origin)links.add(url.href);}for(const link of links){const r=await fetch(link);assert.equal(r.status,200,link);const u=new URL(link);if(u.hash){const html=await r.text();assert.ok(html.includes(`id="${u.hash.slice(1)}"`),link);}}
for(const asset of ['/tools.js','/toolkit.mjs','/data.mjs'])assert.match((await fetch(origin+asset)).headers.get('content-type'),/javascript/);assert.match((await fetch(origin+'/fonts/inter-latin.woff2')).headers.get('content-type'),/font/);
const missing=await fetch(origin+'/nonexistent-test');assert.equal(missing.status,404);assert.match(missing.headers.get('x-robots-tag'),/noindex/);assert.match(await missing.text(),/Page not found/);assert.equal((await fetch(origin+'/home-care/index.html',{redirect:'manual'})).status,308);
}finally{await new Promise(r=>server.close(r));}});

test('workflow plan preserves the selected claim-volume range',()=>{assert.equal(choices.volume.low,'Fewer than 50 claims per month');assert.equal(choices.volume.medium,'50–250 claims per month');assert.equal(choices.volume.high,'251–1,000 claims per month');assert.equal(choices.volume.large,'More than 1,000 claims per month');});
